# Licensed under the MIT license. See LICENSE file in the project root for full license information.

FROM debian:8.0

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y cmake build-essential git libopenal1 libopenal-dev

